[phases.install]
cmds = [
  "npm ci --prefix client",
  "npm ci --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "npm run build --prefix server"
]

[start]
cmd = "NODE_ENV=production node server/dist/index.js"
